### ISSUE TITLE
Display sprites with imageRendering: 'pixelated' property

### ISSUE THREAD

**Issue by IsoPhoenix** [jcblw/react-sprite-animator#341]
I'm not sure if there's already a way to do this, but upscaling a sprite by setting scale to a fraction makes it fuzzy. I'm wondering if there's a way to specify the imageRendering property for the displayed image, as setting it to 'pixelated' usually removes the blurriness.

Thanks!

**Comment by jcblw** [comment]
This should work right now. I am thinking of using a class name. Are you using the hook or the component?

**Comment by IsoPhoenix** [comment]
I'm using the component at the moment. Here's how I'm trying to specify the property:

```react
<SpriteAnimator
   style={{
      imageRendering: 'pixelated',
      position: 'absolute',
      width: '100px',
   }}
   sprite={body}
   width={32}
   height={32}
   shouldAnimate={false}
   frame={0}
   backgroundSize={'500px'}
/>
```

Not sure if this is how I'm supposed to do it. Could you elaborate a bit more on the class name approach if you think that is better?

**Comment by jcblw** [comment]
The style prop does nothing. We do not extend style into the divs' style prop. The class name is passed to the div, which is why I recommended it.

Here are the [available props](https://github.com/jcblw/react-sprite-animator/blob/master/src/index.js#L8). 

Going to close this issue, since it seems #342 is actually related to this issue.
