### ISSUE TITLE
Dynamic resizing of sprites

### ISSUE THREAD

**Issue by IsoPhoenix** [jcblw/react-sprite-animator#342]
I'm trying to select 32px by 32px sprites from a larger spritesheet, but the sprites display as 32px by 32px. I'd like to take that 32px by 32px sprite from my spritesheet file and dynamically resize it with CSS styles such as "width: '100%'). 

Using the following inline styling in React has no effect:
```react
<SpriteAnimator
   style={{
      imageRendering: 'pixelated',
      position: 'absolute',
      width: '100px',
   }}
   sprite={body}
   width={32}
   height={32}
   shouldAnimate={false}
   frame={0}
/>
```

Are there solutions to this problem?

Thanks!

**Comment by jcblw** [comment]
Do you want the sprite size to resize dynamically? Or the sprite sheet? If you want to change the size of the sprite sheet, it's a background image, so you can pass `backgroundSize` to change the size of the sprite sheet. I would expect you would be able to resize the sprite based on the sprite sheet being resized. 

Doing something like 100% might be difficult because you would need to set the background-size to something like 500% width if there are five sprites per row. If you show more of your use case, I would be happy to help.

**Comment by IsoPhoenix** [comment]
Thank you so much for the quick response!

I'd like the displayed sprite to be able to resize to fill the size of its parent container (in my case, an MUI Box component). Something like below:
```react
<Box sx={{
   width: '20%',
   height: '40%',
   maxHeight: '300px',
   maxWidth: '300px',
   position: 'relative',
}}>
   <SpriteAnimator
      style={{
         imageRendering: 'pixelated',
         position: 'absolute',
         width: '100%',
     }}
     sprite={body}
     width={32}
     height={32}
     shouldAnimate={false}
     frame={0}
     />
</Box>
```

Even though the snippet of my spritesheet file is 32px by 32px, I'd like that sprite to resize to fill the parent Box component.

Thank you so much!

**Comment by jcblw** [comment]
I think you might want to use the hook directly to do this. We do not extend the style props into the sprites' styles.

https://github.com/jcblw/react-sprite-animator/blob/master/src/index.js#L67

That might get you further with your implementation since I think that is one of the main issues you are running into.

**Comment by jcblw** [comment]
Let me know if that works for you! This is getting a little stale so I am going to close it.

**Comment by jcblw** [comment]
Feel free to reopen if its an issue.
